#pragma once
#include <Systems/DraggableObject/DraggableObjectSystem.h>
#include <Systems/Physics/CollisionSystem.h>
#include <Systems/Physics/PhysicsSystem.h>
#include <Systems/PlayerController/PlayerControllerSystem.h>
#include <Systems/Rendering/CameraSystem.h>
#include <Systems/Rendering/RenderingSystem.h>
#include <Systems/RootTransform/PostRootTransformSystem.h>
#include <Systems/RootTransform/PreRootTransformSystem.h>
#include <Systems/SpriteAnim/SpriteAnimSystem.h>
#include <Systems/Enemy/EnemySystem.h>
#include <Systems/Text/TextRenderSystem.h>
#include <Systems/TweenSystem/TweenSystem.h>
#include <Systems/GameSystem/GameSystem.h>
#include <Systems/Audio/AudioSystem.h>
#include <Systems/ObjectAnchor/ObjectAnchorSystem.h>